# Generated by Django 3.1.2 on 2020-10-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Course_Number', models.IntegerField()),
                ('Insructor_Name', models.CharField(max_length=60)),
                ('Duration', models.FloatField(default=0.0)),
            ],
        ),
    ]
